name: Endpoints test
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install Dependencies
        run: go mod download
  framework_matrix:
    needs: install_dependencies
    strategy:
      matrix:
        framework:
          [chi, gin, fiber, gorilla/mux, httprouter, standard-library, echo]
        driver:
          [mysql, postgres, sqlite, mongo, redis, none]
        advanced:
          [htmx, githubaction, websocket]
        goVersion: ["1.22"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Commit report
        run: |
          git config --global user.name 'testname'
          git config --global user.email 'testemail@users.noreply.github.com'
      - name: build templates
        run: script -q /dev/null -c "go run main.go create -n ${{ matrix.framework }} -f ${{ matrix.framework}} -d ${{matrix.driver}} --advanced true --feature ${{ matrix.advanced }}" /dev/null

      - if: ${{ matrix.advanced == 'htmx' }}
        name: Install Templ
        run: go install github.com/a-h/templ/cmd/templ@latest
      - if: ${{ matrix.advanced == 'htmx' }}
        name: Run templ generate
        run: /home/runner/go/bin/templ generate -path ${{ matrix.framework }}

      - if : ${{ matrix.advanced != 'htmx' }}
        name: Test / Endpoints
        run: |
          cd ${{ matrix.framework }}

          echo "PORT=8088" > .env
          echo "APP_ENV=local" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=blueprint" >> .env
          echo "DB_USERNAME=melkey" >> .env
          echo "DB_PASSWORD=password1234" >> .env

          make run &
          sleep 5
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" localhost:8080)
          if [ $STATUS_CODE -ne 200 ]; then
            echo "Error: Non-200 status code received ($STATUS_CODE)"
            exit 1
          fi
      
      - if : ${{ matrix.driver != 'none' && matrix.advanced != 'htmx'}}
        name: Test /health Endpoints
        run: |
          cd ${{ matrix.framework }}

          echo "PORT=8088" > .env
          echo "APP_ENV=local" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=blueprint" >> .env
          echo "DB_USERNAME=melkey" >> .env
          echo "DB_PASSWORD=password1234" >> .env

          make run &
          sleep 5
          make docker-run &
          sleep 15
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" localhost:8080/health)
          if [ $STATUS_CODE -ne 200 ]; then
            echo "Error: Non-200 status code received ($STATUS_CODE)"
            exit 1
          fi